### ISSUE TITLE
Поддерживается ли библиотека?

### ISSUE THREAD

**Issue by q00Dree** [devopsalexandr/CianParser#1]
Доброго времени суток. 
Хотел сегодня воспользоваться вашей библиотекой, но столкнулся с ошибкой.

![image](https://user-images.githubusercontent.com/41568398/208198022-585371e6-4e1b-4b90-bb22-12b5d866721c.png)

Возможно дело в редиректе через 5 секунд? Ниже часть html, которая попадает в метод **GetOffersOnPageFromHtml**.

```
<noscript>
        <h1 style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1>
    </noscript>
    <div id="cf-content">
        <div id="cf-bubbles">
            <div class="bubbles"></div>
            <div class="bubbles"></div>
            <div class="bubbles"></div>
        </div>
        <h1>Checking your browser before accessing www.cian.ru.</h1>
        <div id="no-cookie-warning" class="cookie-warning" style="display:none">
            <p style="color:#bd2426;">Please enable Cookies and reload the page</p>
        </div>
        <p>This process is automatic. Your browser will redirect to your requested content shortly.</p>
        <p id="cf-spinner-allow-5-secs">Please allow up to 5 seconds...</p>
        <p id="cf-spinner-redirecting" style="display:none">Redirecting...</p>
    </div>
```

Если не сложно, могли бы Вы актуализировать код?

С уважением.

**Comment by devopsalexandr** [comment]
Добрый день, библиотека больше не поддерживается, могу актуализировать ее
платно под ваши нужды

сб, 17 дек. 2022 г. в 02:19, Artur Safiullin ***@***.***>:

**Comment by q00Dree** [comment]
Понял, спасибо за ответ.
